### ISSUE TITLE
Various Backpack Mods that could be supported.

### ISSUE THREAD

**Issue by tedthedragon** [dastrukar/hdest-wimp#4]
- Wallet by Icarus (https://dastrukar.gitlab.io/hddons-list/#utilities:wallet-icarus)
- Purse by Mohl, likely also needs updating to function with Merchant though. (https://dastrukar.gitlab.io/hddons-list/#utilities:pursejurse-mohl)
- Gunsmithing Pouch by Mohl, likely also needs updating to function with Merchant though. (https://dastrukar.gitlab.io/hddons-list/#utilities:pursejurse-mohl)
- Gear Boxes by FDA (https://dastrukar.gitlab.io/hddons-list/#utilities:gearboxes-fda)

**Comment by dastrukar** [comment]
Correct me if I'm wrong, but doesn't the wallet and purse only store one item?
If so, I don't really see a reason to support them. (aside from visual consistency)

**Comment by tedthedragon** [comment]
Wallet and purse, currently, do only hold one item though visual consistency likely would be nice in my books.

**Comment by dastrukar** [comment]
Fair enough, I'll try adding support for them soon.

**Comment by dastrukar** [comment]
3 out of 4 of the suggested mods are now supported. (Gunsmith Pouch, Wallet, Gear Boxes)
Will be doing Purse later.
Let me know if Gunsmith Pouch has any problems, as I had to modify the mod to get it running.

**Comment by dastrukar** [comment]
All the mods listed should be supported now. Sorry that it took so long.
Feel free to reopen this/create a new issue if any of the patches don't work as intended.
