### ISSUE TITLE
[ammo pouch addon] inventory is getting changed when dropped

### ISSUE THREAD

**Issue by Underqualified-Gunman** [dastrukar/hdest-wimp#8]
been noticing some wierd behavior with the UAS ammo pouch when putting 45 acp in it with more than 1 pouch on the player. when dropped and picked up it gets converted into other round types. ussually 7mm and 12 guage.

test this with 
hideous latest
uas latest
bullet lib recasted latest
hdest wimp latest
and the UAS ammo pouch latest

give your self 4 ammo pouches and 300 of 45 acp (45c) and 9mm 
drop the ammo pouches on the floor and notice the contents change.
seems to get worse the more ammo types that exist as well.

**Comment by dastrukar** [comment]
whoops, github didn't notify me about this
will look into it soon

**Comment by dastrukar** [comment]
can't seem to replicate it.
Got 4 ammo pouches, shoved 300 45 ACP rounds and 300 9mm rounds into them, and dropped them all. The contents didn't change. Same load order too.
Will try with more ammo types later.
EDIT: also tried with `hd_myloadout "apo 4. 45c 300. 9mm 300"`. contents didn't change.

**Comment by dastrukar** [comment]
yeah, can't replicate this
unless there's something that i'm missing, the pouch is behaving as intended
i.e: you drop the pouch and it takes away the ammo type and puts in the dropped pouch. picking it up gives whatever was in that pouch back.
that said, WIMP shouldn't be doing anything that affects the inventory. all the storage stuff is handled by the original backpack code, and WIMP does some tricks to make it extract/insert the right item.

do let me know if i did the testing wrong:

load order:
- HideousDestructor [main]
- Ugly-as-Sin [master]
- HDBulletLib-Recasted [main]
- WIMP [master]
- wimp-patches/uas-ammo_pouch [master]

tested with:
- `hd_give "apo 4"` `hd_give "45c 300"` `hd_give "9mm 300"`
- `hd_myloadout "apo 4. 45c 300. 9mm 300"`
- `hd_myloadout "apo 10. 50r 10. slu 10. 5sw 10. 5ld 10. omg 10. 45c 10. 10M 10"`

**Comment by Underqualified-Gunman** [comment]
hmm will make sure i wasn't somehow loading something else/an old version. 
it entirely possible i have been since my HD mods folder is getting more bloated and disorganized overtime.

**Comment by dastrukar** [comment]
since this has been inactive for about a month now, i'll just assume that this problem isn't related to wimp.
